// Generated by Haxe 3.3.0
package haxe.ds._Vector;

import haxe.root.*;

public final class Vector_Impl_
{
	
	
	public class func toArray <T>(this1 : haxe.root.Array<T?>) ->  haxe.root.Array<T?>
	{
		//line 190 "/home/ron/haxe/std/haxe/ds/Vector.hx"
		var a : haxe.root.Array<T?> = haxe.root.Array<T?>()
		//line 191 "/home/ron/haxe/std/haxe/ds/Vector.hx"
		var len : Int = (this1) as haxe.root.Array<T?>!.length
		//line 196 "/home/ron/haxe/std/haxe/ds/Vector.hx"
		{
			//line 196 "/home/ron/haxe/std/haxe/ds/Vector.hx"
			var _g1 : Int = 0
			//line 196 "/home/ron/haxe/std/haxe/ds/Vector.hx"
			while ((_g1 < len))
			{
				//line 196 "/home/ron/haxe/std/haxe/ds/Vector.hx"
				var i : Int = _g1++
				//line 197 "/home/ron/haxe/std/haxe/ds/Vector.hx"
				a!.__set(i, ((this1) as haxe.root.Array<T?>!.__get(i)) as T)
			}
			
		}
		
		//line 198 "/home/ron/haxe/std/haxe/ds/Vector.hx"
		return a
	}
	
	
}


