// Generated by Haxe 3.3.0
package swift;

import haxe.root.*;

@SuppressWarnings(value={})
public class NativeArray<T>
{
	public NativeArray(Int len)
	{
		 self.init(len)
	}
	
	
	public Int get_length()
	{
		return self.count
	}
	
	
}


