// Generated by Haxe 3.3.0
package haxe.lang;

import haxe.root.*;

@SuppressWarnings(value={})
public class DynamicObject extends haxe.lang.HxObject
{
	@Override public String? toString()
	{
		//line 46 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		[ !TypeError Void -> String ] ts = haxe.root.Reflect.field(this, "toString")
		//line 47 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if (( ts != nil )) 
		{
			//line 48 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return ts()
		}
		
		//line 49 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		haxe.root.StringBuf ret = new haxe.root.StringBuf()
		//line 50 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		ret.add("{")
		//line 51 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		Bool first = true
		//line 52 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		{
			//line 52 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			Int _g = 0
			//line 52 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			haxe.root.Array<String??> _g1 = haxe.root.Reflect.fields(this)
			//line 52 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			while (( _g < _g1.length ))
			{
				//line 52 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				String? f = _g1[_g]
				//line 52 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				 ++ _g
				//line 54 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				if (first) 
				{
					//line 55 "/home/ron/haxe/std/swift/internal/HxObject.hx"
					first = false
				}
				else
				{
					//line 57 "/home/ron/haxe/std/swift/internal/HxObject.hx"
					ret.add(",")
				}
				
				//line 58 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				ret.add(" ")
				//line 58 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				ret.add(f)
				//line 59 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				ret.add(" : ")
				//line 60 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				ret.add(haxe.root.Reflect.field(this, f))
			}
			
		}
		
		//line 62 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if ( ! (first) ) 
		{
			//line 62 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			ret.add(" ")
		}
		
		//line 63 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		ret.add("}")
		//line 64 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		return ret.toString()
	}
	
	
}


