// Generated by Haxe 3.3.0
package haxe.lang;

import haxe.root.*;

@SuppressWarnings(value={})
public class Enum
{
	public Enum(Int index)
	{
		//line 75 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this.index = index
	}
	
	
	public final Int index
	
	public String? getTag()
	{
		//line 80 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		throw "Not Implemented"
	}
	
	
	public haxe.root.Array<Any??> getParams()
	{
		//line 85 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		return new haxe.root.Array<Any??>(new Array<Any?>?{})
	}
	
	
	@Override public String? toString()
	{
		//line 90 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		return this.getTag()
	}
	
	
}


