// Generated by Haxe 3.3.0
package haxe.lang;

import haxe.root.*;

@SuppressWarnings(value={})
public class ParamEnum extends haxe.lang.Enum
{
	public ParamEnum(Int index, haxe.root.Array params)
	{
		//line 101 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		super(index)
		//line 102 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this.params = params
	}
	
	
	public final haxe.root.Array params
	
	@Override public haxe.root.Array<Any??> getParams()
	{
		//line 107 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if (( this.params == nil )) 
		{
			//line 107 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return new haxe.root.Array<Any??>(new Array<Any?>?{})
		}
		else
		{
			//line 107 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return ((haxe.root.Array<Any??>) (haxe.ds._Vector.Vector_Impl_.toArray(this.params)) )
		}
		
	}
	
	
	@Override public String? toString()
	{
		//line 112 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if (( ( this.params == nil ) || ( ((haxe.root.Array) (this.params) ).length == 0 ) )) 
		{
			//line 112 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return this.getTag()
		}
		
		//line 113 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		haxe.root.StringBuf ret = new haxe.root.StringBuf()
		//line 114 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		ret.add(this.getTag())
		//line 114 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		ret.add("(")
		//line 115 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		Bool first = true
		//line 116 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		{
			//line 116 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			Int _g = 0
			//line 116 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			haxe.root.Array _g1 = this.params
			//line 116 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			while (( _g < ((haxe.root.Array) (_g1) ).length ))
			{
				//line 116 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				Any? p = ((Any?) (((haxe.root.Array) (_g1) )[_g]) )
				//line 116 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				 ++ _g
				//line 118 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				if (first) 
				{
					//line 119 "/home/ron/haxe/std/swift/internal/HxObject.hx"
					first = false
				}
				else
				{
					//line 121 "/home/ron/haxe/std/swift/internal/HxObject.hx"
					ret.add(",")
				}
				
				//line 122 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				ret.add(p)
			}
			
		}
		
		//line 124 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		ret.add(")")
		//line 125 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		return ret.toString()
	}
	
	
	@Override public Bool equals(Any? obj)
	{
		//line 130 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if (( obj == this )) 
		{
			//line 131 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return true
		}
		
		//line 132 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		haxe.lang.ParamEnum obj1 = ( (haxe.root.Std.is(obj, haxe.lang.ParamEnum)) ? (((haxe.lang.ParamEnum) (obj) )) : (nil) )
		//line 134 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if ( ! ((( ( ( obj1 != nil ) && haxe.root.Std.is(obj1, haxe.root.Type.getEnum(((Any?) (this) ))) ) && ( obj1.index == this.index ) ))) ) 
		{
			//line 135 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return false
		}
		
		//line 136 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if (( obj1.params == this.params )) 
		{
			//line 137 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return true
		}
		
		//line 138 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		Int len = 0
		//line 139 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		Bool tmp = false
		//line 139 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if ( ! ((( ( obj1.params == nil ) || ( this.params == nil ) ))) ) 
		{
			//line 139 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			len = ((haxe.root.Array) (this.params) ).length
			//line 139 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			tmp = ( len != ((haxe.root.Array) (obj1.params) ).length )
		}
		else
		{
			//line 139 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			tmp = true
		}
		
		//line 139 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if (tmp) 
		{
			//line 140 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return false
		}
		
		//line 141 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		{
			//line 141 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			Int _g1 = 0
			//line 141 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			Int _g = len
			//line 141 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			while (( _g1 < _g ))
			{
				//line 141 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				Int i = _g1++
				//line 143 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				if ( ! (haxe.root.Type.enumEq(((Any?) (((haxe.root.Array) (obj1.params) )[i]) ), ((Any?) (((haxe.root.Array) (this.params) )[i]) ))) ) 
				{
					//line 144 "/home/ron/haxe/std/swift/internal/HxObject.hx"
					return false
				}
				
			}
			
		}
		
		//line 146 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		return true
	}
	
	
	@Override public Int hashCode()
	{
		//line 151 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		Int h = 19
		//line 152 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if (( this.params != nil )) 
		{
			//line 152 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			Int _g = 0
			//line 152 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			haxe.root.Array _g1 = this.params
			//line 152 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			while (( _g < ((haxe.root.Array) (_g1) ).length ))
			{
				//line 152 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				Any? p = ((Any?) (((haxe.root.Array) (_g1) )[_g]) )
				//line 152 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				 ++ _g
				//line 154 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				h *= 31
				//line 155 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				if (( p != nil )) 
				{
					//line 156 "/home/ron/haxe/std/swift/internal/HxObject.hx"
					h += p.hashCode()
				}
				
			}
			
		}
		
		//line 158 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		h += this.index
		//line 159 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		return h
	}
	
	
}


