// Generated by Haxe 3.3.0
package haxe.lang;

import haxe.root.*;

@SuppressWarnings(value={})
public class Runtime
{
	static
	{
		//line 33 "/home/ron/haxe/std/swift/internal/Runtime.hx"
		haxe.lang.Runtime.undefined = ((Any?) ([ obj decl not supported ]) )
	}
	
	public static Any? undefined
	
	public static Any? closure(Any? obj, String? field)
	{
		
	
	}
	
	
	public static Bool eq(Any? v1, Any? v2)
	{
		
	
	}
	
	
	public static Bool refEq(Any? v1, Any? v2)
	{
		
	
	}
	
	
	public static Bool valEq(Any? v1, Any? v2)
	{
		
	
	}
	
	
	public static Double toDouble(Any? obj)
	{
		
	
	}
	
	
	public static Bool toBool(Any? obj)
	{
		
	
	}
	
	
	public static Int toInt(Any? obj)
	{
		
	
	}
	
	
	public static Int64 toLong(Any? obj)
	{
		//line 86 "/home/ron/haxe/std/swift/internal/Runtime.hx"
		return swift._StdTypes.Int64_Impl_._new()
	}
	
	
	public static Bool isDouble(Any? obj)
	{
		
	
	}
	
	
	public static Bool isInt(Any? obj)
	{
		//line 98 "/home/ron/haxe/std/swift/internal/Runtime.hx"
		return false
	}
	
	
	public static Bool slowHasField(Any? o, String? field)
	{
		
	
	}
	
	
	public static Int compare(Any? v1, Any? v2)
	{
		
	}
	
	
	public static Any? plus(Any? v1, Any? v2)
	{
		
	
	}
	
	
	public static Any? slowGetField(Any? obj, String? field, Bool throwErrors)
	{
		
	
	}
	
	
	public static Any? slowSetField(Any? obj, String? field, Any? value)
	{
		
	
	}
	
	
	public static Any? slowCallField(Any? obj, String? field, haxe.root.Array args)
	{
		
	
	}
	
	
	public static Any? callField(Any? obj, String? field, haxe.root.Array args)
	{
		
	
	}
	
	
	public static Any? getField(Any? obj, String? field, Bool throwErrors)
	{
		
	
	}
	
	
	public static Double getField_f(Any? obj, String? field, Bool throwErrors)
	{
		
	
	}
	
	
	public static Any? setField(Any? obj, String? field, Any? value)
	{
		
	
	}
	
	
	public static Double setField_f(Any? obj, String? field, Double value)
	{
		
	
	}
	
	
	public static String? toString(Any? obj)
	{
		//line 179 "/home/ron/haxe/std/swift/internal/Runtime.hx"
		return ""
	}
	
	
	public static Bool isFinite(Double v)
	{
		//line 184 "/home/ron/haxe/std/swift/internal/Runtime.hx"
		return false
	}
	
	
}


