// Generated by Haxe 3.3.0
package swift;

import haxe.root.*;

public class NativeArray<T>
{
	public init(len : Int) ->  Void
	{
		 self.init(len)
	}
	
	
	public func get_length() ->  Int
	{
		return self.count
	}
	
	
}


