// Generated by Haxe 3.3.0
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={})
public class Main
{
	public static void main(String[] args)
	{
		main();
	}
	
	public static main()
	{
		//line 8 "/home/ron/haxesrc/TestTypedefSyntax/Main.hx"
		Any? myTuple = [ obj decl not supported ]
		//line 12 "/home/ron/haxesrc/TestTypedefSyntax/Main.hx"
		haxe.Log.trace(myTuple.add(myTuple.myInt1, myTuple.myInt2), [ obj decl not supported ])
	}
	
	
}


