// Generated by Haxe 3.3.0
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={})
public class Std
{
	public static Bool is(Any? v, Any? t)
	{
		return (v is t)
	}
	
	
	public static String? string(Any? s)
	{
		return (s is String) ? s as! String : ""
	}
	
	
	public static Int _int(Double x)
	{
		return Int(x)
	}
	
	
	public static Any? parseInt(String? x)
	{
		return (x != nil) ? Int(x) : nil
	}
	
	
	public static Double parseFloat(String? x)
	{
		return (x != nil) ? Float(x) : nil
	}
	
	
	public static <T, S> S instance(T value, Any? c)
	{
		return value as? c
	}
	
	
	public static Int random(Int x)
	{
		//line 59 "/home/ron/haxe/std/swift/_std/Std.hx"
		if (( x <= 0 )) 
		{
			//line 59 "/home/ron/haxe/std/swift/_std/Std.hx"
			return 0
		}
		
		//line 60 "/home/ron/haxe/std/swift/_std/Std.hx"
		return haxe.root.Std._int(( haxe.root.Math.random() * x ))
	}
	
	
}


