// Generated by Haxe 3.3.0
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={})
public class StringBuf
{
	public StringBuf()
	{
	}
	
	
	
	
	public <T> add(T x)
	{
	}
	
	
	@Override public String? toString()
	{
		//line 45 "/home/ron/haxe/std/swift/_std/StringBuf.hx"
		return nil
	}
	
	
}


