// Generated by Haxe 3.3.0
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={})
public class Type
{
	public static <T> Any? getClass(T o)
	{
		//line 41 "/home/ron/haxe/std/swift/_std/Type.hx"
		return nil
	}
	
	
	public static Any? getEnum(Any? o)
	{
		//line 46 "/home/ron/haxe/std/swift/_std/Type.hx"
		return nil
	}
	
	
	public static Any? getSuperClass(Any? c)
	{
		//line 51 "/home/ron/haxe/std/swift/_std/Type.hx"
		return nil
	}
	
	
	public static String? getClassName(Any? c)
	{
		//line 55 "/home/ron/haxe/std/swift/_std/Type.hx"
		return ""
	}
	
	
	public static String? getEnumName(Any? e)
	{
		//line 59 "/home/ron/haxe/std/swift/_std/Type.hx"
		return ""
	}
	
	
	public static Any? resolveClass(String? name)
	{
		//line 64 "/home/ron/haxe/std/swift/_std/Type.hx"
		return nil
	}
	
	
	public static Any? resolveEnum(String? name)
	{
		
		
	
	}
	
	
	public static <T> T createInstance(Any? cl, haxe.root.Array args)
	{
		
			
	
	}
	
	
	public static <T> T createEmptyInstance(Any? cl)
	{
		//line 89 "/home/ron/haxe/std/swift/_std/Type.hx"
		return nil
	}
	
	
	public static <T> T createEnum(Any? e, String? constr, haxe.root.Array params)
	{
		
		
	
	}
	
	
	public static <T> T createEnumIndex(Any? e, Int index, haxe.root.Array params)
	{
		//line 102 "/home/ron/haxe/std/swift/_std/Type.hx"
		return haxe.root.Type.createEnum(e, haxe.root.Type.getEnumConstructs(e)[index], params)
	}
	
	
	public static haxe.root.Array<String??> getInstanceFields(Any? c)
	{
		
		
	
	}
	
	
	public static haxe.root.Array<String??> getClassFields(Any? c)
	{
		
		
	
	}
	
	
	public static haxe.root.Array<String??> getEnumConstructs(Any? e)
	{
		//line 120 "/home/ron/haxe/std/swift/_std/Type.hx"
		return nil
	}
	
	
	public static haxe.root.ValueType typeof(Any? v)
	{
		
	
	
	}
	
	
	public static <T> Bool enumEq(T a, T b)
	{
		
			
	
	}
	
	
	public static String? enumConstructor(Any? e)
	{
		
	
	
	}
	
	
	public static haxe.root.Array enumParameters(Any? e)
	{
		
	
	
	}
	
	
	public static Int enumIndex(Any? e)
	{
		
	
	}
	
	
	public static <T> haxe.root.Array<T?> allEnums(Any? e)
	{
		//line 164 "/home/ron/haxe/std/swift/_std/Type.hx"
		return nil
	}
	
	
}


