// Generated by Haxe 3.3.0
package haxe.lang;

import haxe.root.*;

public class DynamicObject : haxe.lang.HxObject
{
	public init() ->  Void
	{
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this!.__hx_hashes = []
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this!.__hx_dynamics = []
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this!.__hx_hashes_f = []
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this!.__hx_dynamics_f = []
	}
	
	
	public init(__hx_hashes : Array<String?>, __hx_dynamics : Array<Any?>, __hx_hashes_f : Array<String?>, __hx_dynamics_f : Array<Double>) ->  Void
	{
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this!.__hx_hashes = __hx_hashes
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this!.__hx_dynamics = __hx_dynamics
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this!.__hx_hashes_f = __hx_hashes_f
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this!.__hx_dynamics_f = __hx_dynamics_f
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this!.__hx_length = haxe.lang.Runtime.getField(__hx_hashes, "length", true)
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this!.__hx_length_f = haxe.lang.Runtime.getField(__hx_hashes_f, "length", true)
	}
	
	
	public func toString() ->  String?
	{
		//line 46 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		var ts : (  ) -> String? = haxe.lang.Runtime.getField(this, "toString", false)
		//line 47 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if ((ts != nil)) 
		{
			//line 48 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return ts()
		}
		
		//line 49 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		var ret : haxe.root.StringBuf = haxe.root.StringBuf()
		//line 50 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		ret!.add("{")
		//line 51 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		var first : Bool = true
		//line 52 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		{
			//line 52 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			var _g : Int = 0
			//line 52 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			var _g1 : haxe.root.Array<String??> = haxe.root.Reflect.fields(this)
			//line 52 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			while ((_g < _g1!.length))
			{
				//line 52 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				var f : String? = _g1!.__get(_g)
				//line 52 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				 ++ _g
				//line 54 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				if (first) 
				{
					//line 55 "/home/ron/haxe/std/swift/internal/HxObject.hx"
					first = false
				}
				else
				{
					//line 57 "/home/ron/haxe/std/swift/internal/HxObject.hx"
					ret!.add(",")
				}
				
				//line 58 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				ret!.add(" ")
				//line 58 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				ret!.add(f)
				//line 59 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				ret!.add(" : ")
				//line 60 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				ret!.add(haxe.root.Reflect.field(this, f))
			}
			
		}
		
		//line 62 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if ( ! (first) ) 
		{
			//line 62 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			ret!.add(" ")
		}
		
		//line 63 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		ret!.add("}")
		//line 64 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		return ret!.toString()
	}
	
	
	public dynamic func __hx_hashes Array<String?>
	
	public dynamic func __hx_dynamics Array<Any?>
	
	public dynamic func __hx_hashes_f Array<String?>
	
	public dynamic func __hx_dynamics_f Array<Double>
	
	public dynamic func __hx_length Int
	
	public dynamic func __hx_length_f Int
	
	public override func __hx_deleteField(field : String?) ->  Bool
	{
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		var res : Int = haxe.lang.FieldLookup.findHash(field, this!.__hx_hashes, this!.__hx_length)
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if ((res >= 0)) 
		{
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			haxe.lang.FieldLookup.removeString(this!.__hx_hashes, this!.__hx_length, res)
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			haxe.lang.FieldLookup.removeDynamic(this!.__hx_dynamics, this!.__hx_length, res)
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			this!.__hx_length--
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return true
		}
		else
		{
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			res = haxe.lang.FieldLookup.findHash(field, this!.__hx_hashes_f, this!.__hx_length_f)
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			if ((res >= 0)) 
			{
				//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				haxe.lang.FieldLookup.removeString(this!.__hx_hashes_f, this!.__hx_length_f, res)
				//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				haxe.lang.FieldLookup.removeFloat(this!.__hx_dynamics_f, this!.__hx_length_f, res)
				//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				this!.__hx_length_f--
				//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				return true
			}
			
		}
		
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		return false
	}
	
	
	public override func __hx_lookupField(field : String?, throwErrors : Bool, isCheck : Bool) ->  Any?
	{
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		var res : Int = haxe.lang.FieldLookup.findHash(field, this!.__hx_hashes, this!.__hx_length)
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if ((res >= 0)) 
		{
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return this!.__hx_dynamics[res]
		}
		else
		{
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			res = haxe.lang.FieldLookup.findHash(field, this!.__hx_hashes_f, this!.__hx_length_f)
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			if ((res >= 0)) 
			{
				//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				return this!.__hx_dynamics_f[res]
			}
			
		}
		
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if (isCheck) 
		{
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return __undefined__
		}
		else
		{
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return nil
		}
		
	}
	
	
	public override func __hx_lookupField_f(field : String?, throwErrors : Bool) ->  Double
	{
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		var res : Int = haxe.lang.FieldLookup.findHash(field, this!.__hx_hashes_f, this!.__hx_length_f)
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if ((res >= 0)) 
		{
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return this!.__hx_dynamics_f[res]
		}
		else
		{
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			res = haxe.lang.FieldLookup.findHash(field, this!.__hx_hashes, this!.__hx_length)
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			if ((res >= 0)) 
			{
				//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				return this!.__hx_dynamics[res]
			}
			
		}
		
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		return 0.0
	}
	
	
	public override func __hx_lookupSetField(field : String?, value : Any?) ->  Any?
	{
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		var res : Int = haxe.lang.FieldLookup.findHash(field, this!.__hx_hashes, this!.__hx_length)
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if ((res >= 0)) 
		{
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return this!.__hx_dynamics[res] = value
		}
		else
		{
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			var res2 : Int = haxe.lang.FieldLookup.findHash(field, this!.__hx_hashes_f, this!.__hx_length_f)
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			if ((res2 >= 0)) 
			{
				//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				haxe.lang.FieldLookup.removeString(this!.__hx_hashes_f, this!.__hx_length_f, res2)
				//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				haxe.lang.FieldLookup.removeFloat(this!.__hx_dynamics_f, this!.__hx_length_f, res2)
				//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				this!.__hx_length_f--
			}
			
		}
		
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this!.__hx_hashes = haxe.lang.FieldLookup.insertString(this!.__hx_hashes, this!.__hx_length,  ~ (res) , field)
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this!.__hx_dynamics = haxe.lang.FieldLookup.insertDynamic(this!.__hx_dynamics, this!.__hx_length,  ~ (res) , value)
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this!.__hx_length++
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		return value
	}
	
	
	public override func __hx_lookupSetField_f(field : String?, value : Double) ->  Double
	{
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		var res : Int = haxe.lang.FieldLookup.findHash(field, this!.__hx_hashes_f, this!.__hx_length_f)
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if ((res >= 0)) 
		{
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return this!.__hx_dynamics_f[res] = value
		}
		else
		{
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			var res2 : Int = haxe.lang.FieldLookup.findHash(field, this!.__hx_hashes, this!.__hx_length)
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			if ((res2 >= 0)) 
			{
				//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				haxe.lang.FieldLookup.removeString(this!.__hx_hashes, this!.__hx_length, res2)
				//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				haxe.lang.FieldLookup.removeDynamic(this!.__hx_dynamics, this!.__hx_length, res2)
				//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				this!.__hx_length--
			}
			
		}
		
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this!.__hx_hashes_f = haxe.lang.FieldLookup.insertString(this!.__hx_hashes_f, this!.__hx_length_f,  ~ (res) , field)
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this!.__hx_dynamics_f = haxe.lang.FieldLookup.insertFloat(this!.__hx_dynamics_f, this!.__hx_length_f,  ~ (res) , value)
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this!.__hx_length_f++
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		return value
	}
	
	
	public override func __hx_getFields(baseArr : haxe.root.Array<String??>) ->  Void
	{
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		var i : Int = 0
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		i = 0
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		while ((i < this!.__hx_length))
		{
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			baseArr!.push(this!.__hx_hashes[i++])
		}
		
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		i = 0
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		while ((i < this!.__hx_length_f))
		{
			//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			baseArr!.push(this!.__hx_hashes_f[i++])
		}
		
		//line 42 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		super!.__hx_getFields(baseArr)
	}
	
	
}


