// Generated by Haxe 3.3.0
package haxe.lang;

import haxe.root.*;

public class Enum
{
	public init(index : Int) ->  Void
	{
		//line 75 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this!.index = index
	}
	
	
	public dynamic func index Int
	
	public func getTag() ->  String?
	{
		//line 80 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		throw "Not Implemented"
	}
	
	
	public func getParams() ->  haxe.root.Array<Any?>
	{
		//line 85 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		return haxe.root.Array<Any?>([])
	}
	
	
	public func toString() ->  String?
	{
		//line 90 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		return this!.getTag()
	}
	
	
}


