// Generated by Haxe 3.3.0
package haxe.lang;

import haxe.root.*;

public class FieldLookup : haxe.lang.HxObject
{
	public class func hash(s : String?) ->  Int
	{
		
	
	}
	
	
	public class func findHash(hash : String?, hashs : Array<String?>, length : Int) ->  Int
	{
		//line 38 "/home/ron/haxe/std/swift/internal/FieldLookup.hx"
		return 0
	}
	
	
	public class func removeString(a : Array<String?>, length : Int, pos : Int) ->  Void
	{
	}
	
	
	public class func removeFloat(a : Array<Double>, length : Int, pos : Int) ->  Void
	{
	}
	
	
	public class func removeDynamic(a : Array<Any?>, length : Int, pos : Int) ->  Void
	{
	}
	
	
	public class func insertString(a : Array<String?>, length : Int, pos : Int, x : String?) ->  Array<String?>
	{
		//line 56 "/home/ron/haxe/std/swift/internal/FieldLookup.hx"
		return nil
	}
	
	
	public class func insertFloat(a : Array<Double>, length : Int, pos : Int, x : Double) ->  Array<Double>
	{
		//line 57 "/home/ron/haxe/std/swift/internal/FieldLookup.hx"
		return nil
	}
	
	
	public class func insertDynamic(a : Array<Any?>, length : Int, pos : Int, x : Any?) ->  Array<Any?>
	{
		//line 58 "/home/ron/haxe/std/swift/internal/FieldLookup.hx"
		return nil
	}
	
	
}


