// Generated by Haxe 3.3.0
package haxe.lang;

import haxe.root.*;

public class Function
{
	public init(arity : Int, type : Int) ->  Void
	{
		//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
		this!.__fn_type = type
		//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
		this!.__hx_arity = arity
	}
	
	
	public func __hx_invokeDynamic(__fn_dynargs : haxe.root.Array) ->  Any?
	{
		//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
		switch (( ((__fn_dynargs == nil)) ? (0) : (__fn_dynargs!.length) ))
		{
			case 0:
			{
				//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
				return this!.__hx_invoke0_o()
			}
			
			
			case 1:
			{
				//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
				return this!.__hx_invoke1_o(0.0, (__fn_dynargs!.__get(0)) as Any?)
			}
			
			
			case 2:
			{
				//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
				return this!.__hx_invoke2_o(0.0, (__fn_dynargs!.__get(0)) as Any?, 0.0, (__fn_dynargs!.__get(1)) as Any?)
			}
			
			
			case 3:
			{
				//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
				return this!.__hx_invoke3_o(0.0, (__fn_dynargs!.__get(0)) as Any?, 0.0, (__fn_dynargs!.__get(1)) as Any?, 0.0, (__fn_dynargs!.__get(2)) as Any?)
			}
			
			
			case 4:
			{
				//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
				return this!.__hx_invoke4_o(0.0, (__fn_dynargs!.__get(0)) as Any?, 0.0, (__fn_dynargs!.__get(1)) as Any?, 0.0, (__fn_dynargs!.__get(2)) as Any?, 0.0, (__fn_dynargs!.__get(3)) as Any?)
			}
			
			
			case 5:
			{
				//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
				return this!.__hx_invoke5_o(0.0, (__fn_dynargs!.__get(0)) as Any?, 0.0, (__fn_dynargs!.__get(1)) as Any?, 0.0, (__fn_dynargs!.__get(2)) as Any?, 0.0, (__fn_dynargs!.__get(3)) as Any?, 0.0, (__fn_dynargs!.__get(4)) as Any?)
			}
			
			
			case 6:
			{
				//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
				return this!.__hx_invoke6_o(0.0, (__fn_dynargs!.__get(0)) as Any?, 0.0, (__fn_dynargs!.__get(1)) as Any?, 0.0, (__fn_dynargs!.__get(2)) as Any?, 0.0, (__fn_dynargs!.__get(3)) as Any?, 0.0, (__fn_dynargs!.__get(4)) as Any?, 0.0, (__fn_dynargs!.__get(5)) as Any?)
			}
			
			
			default:
			{
				//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
				throw "Too many arguments"
			}
			
		}
		
	}
	
	
	public dynamic func __fn_type Int
	
	public dynamic func __hx_arity Int
	
	public func __hx_invoke6_o(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?, __fn_float3 : Double, __fn_dyn3 : Any?, __fn_float4 : Double, __fn_dyn4 : Any?, __fn_float5 : Double, __fn_dyn5 : Any?, __fn_float6 : Double, __fn_dyn6 : Any?) ->  Any?
	{
		//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
		if ((this!.__fn_type != 1)) 
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			throw "Wrong number of arguments"
		}
		else
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			return this!.__hx_invoke6_f(__fn_float1, __fn_dyn1, __fn_float2, __fn_dyn2, __fn_float3, __fn_dyn3, __fn_float4, __fn_dyn4, __fn_float5, __fn_dyn5, __fn_float6, __fn_dyn6)
		}
		
	}
	
	
	public func __hx_invoke6_f(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?, __fn_float3 : Double, __fn_dyn3 : Any?, __fn_float4 : Double, __fn_dyn4 : Any?, __fn_float5 : Double, __fn_dyn5 : Any?, __fn_float6 : Double, __fn_dyn6 : Any?) ->  Double
	{
		//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
		if ((this!.__fn_type != 0)) 
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			throw "Wrong number of arguments"
		}
		else
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			return this!.__hx_invoke6_o(__fn_float1, __fn_dyn1, __fn_float2, __fn_dyn2, __fn_float3, __fn_dyn3, __fn_float4, __fn_dyn4, __fn_float5, __fn_dyn5, __fn_float6, __fn_dyn6)
		}
		
	}
	
	
	public func __hx_invoke5_o(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?, __fn_float3 : Double, __fn_dyn3 : Any?, __fn_float4 : Double, __fn_dyn4 : Any?, __fn_float5 : Double, __fn_dyn5 : Any?) ->  Any?
	{
		//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
		if ((this!.__fn_type != 1)) 
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			throw "Wrong number of arguments"
		}
		else
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			return this!.__hx_invoke5_f(__fn_float1, __fn_dyn1, __fn_float2, __fn_dyn2, __fn_float3, __fn_dyn3, __fn_float4, __fn_dyn4, __fn_float5, __fn_dyn5)
		}
		
	}
	
	
	public func __hx_invoke5_f(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?, __fn_float3 : Double, __fn_dyn3 : Any?, __fn_float4 : Double, __fn_dyn4 : Any?, __fn_float5 : Double, __fn_dyn5 : Any?) ->  Double
	{
		//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
		if ((this!.__fn_type != 0)) 
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			throw "Wrong number of arguments"
		}
		else
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			return this!.__hx_invoke5_o(__fn_float1, __fn_dyn1, __fn_float2, __fn_dyn2, __fn_float3, __fn_dyn3, __fn_float4, __fn_dyn4, __fn_float5, __fn_dyn5)
		}
		
	}
	
	
	public func __hx_invoke4_o(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?, __fn_float3 : Double, __fn_dyn3 : Any?, __fn_float4 : Double, __fn_dyn4 : Any?) ->  Any?
	{
		//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
		if ((this!.__fn_type != 1)) 
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			throw "Wrong number of arguments"
		}
		else
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			return this!.__hx_invoke4_f(__fn_float1, __fn_dyn1, __fn_float2, __fn_dyn2, __fn_float3, __fn_dyn3, __fn_float4, __fn_dyn4)
		}
		
	}
	
	
	public func __hx_invoke4_f(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?, __fn_float3 : Double, __fn_dyn3 : Any?, __fn_float4 : Double, __fn_dyn4 : Any?) ->  Double
	{
		//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
		if ((this!.__fn_type != 0)) 
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			throw "Wrong number of arguments"
		}
		else
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			return this!.__hx_invoke4_o(__fn_float1, __fn_dyn1, __fn_float2, __fn_dyn2, __fn_float3, __fn_dyn3, __fn_float4, __fn_dyn4)
		}
		
	}
	
	
	public func __hx_invoke3_o(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?, __fn_float3 : Double, __fn_dyn3 : Any?) ->  Any?
	{
		//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
		if ((this!.__fn_type != 1)) 
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			throw "Wrong number of arguments"
		}
		else
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			return this!.__hx_invoke3_f(__fn_float1, __fn_dyn1, __fn_float2, __fn_dyn2, __fn_float3, __fn_dyn3)
		}
		
	}
	
	
	public func __hx_invoke3_f(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?, __fn_float3 : Double, __fn_dyn3 : Any?) ->  Double
	{
		//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
		if ((this!.__fn_type != 0)) 
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			throw "Wrong number of arguments"
		}
		else
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			return this!.__hx_invoke3_o(__fn_float1, __fn_dyn1, __fn_float2, __fn_dyn2, __fn_float3, __fn_dyn3)
		}
		
	}
	
	
	public func __hx_invoke2_o(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?) ->  Any?
	{
		//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
		if ((this!.__fn_type != 1)) 
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			throw "Wrong number of arguments"
		}
		else
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			return this!.__hx_invoke2_f(__fn_float1, __fn_dyn1, __fn_float2, __fn_dyn2)
		}
		
	}
	
	
	public func __hx_invoke2_f(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?) ->  Double
	{
		//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
		if ((this!.__fn_type != 0)) 
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			throw "Wrong number of arguments"
		}
		else
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			return this!.__hx_invoke2_o(__fn_float1, __fn_dyn1, __fn_float2, __fn_dyn2)
		}
		
	}
	
	
	public func __hx_invoke1_o(__fn_float1 : Double, __fn_dyn1 : Any?) ->  Any?
	{
		//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
		if ((this!.__fn_type != 1)) 
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			throw "Wrong number of arguments"
		}
		else
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			return this!.__hx_invoke1_f(__fn_float1, __fn_dyn1)
		}
		
	}
	
	
	public func __hx_invoke1_f(__fn_float1 : Double, __fn_dyn1 : Any?) ->  Double
	{
		//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
		if ((this!.__fn_type != 0)) 
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			throw "Wrong number of arguments"
		}
		else
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			return this!.__hx_invoke1_o(__fn_float1, __fn_dyn1)
		}
		
	}
	
	
	public func __hx_invoke0_o() ->  Any?
	{
		//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
		if ((this!.__fn_type != 1)) 
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			throw "Wrong number of arguments"
		}
		else
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			return this!.__hx_invoke0_f()
		}
		
	}
	
	
	public func __hx_invoke0_f() ->  Double
	{
		//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
		if ((this!.__fn_type != 0)) 
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			throw "Wrong number of arguments"
		}
		else
		{
			//line 32 "/home/ron/haxe/std/swift/internal/Function.hx"
			return this!.__hx_invoke0_o()
		}
		
	}
	
	
}


