// Generated by Haxe 3.3.0
package haxe.lang;

import haxe.root.*;

public interface IHxObject
{
	public func __hx_deleteField(field : String?) ->  Bool
	
	public func __hx_lookupField(field : String?, throwErrors : Bool, isCheck : Bool) ->  Any?
	
	public func __hx_lookupField_f(field : String?, throwErrors : Bool) ->  Double
	
	public func __hx_lookupSetField(field : String?, value : Any?) ->  Any?
	
	public func __hx_lookupSetField_f(field : String?, value : Double) ->  Double
	
	public func __hx_setField_f(field : String?, value : Double, handleProperties : Bool) ->  Double
	
	public func __hx_setField(field : String?, value : Any?, handleProperties : Bool) ->  Any?
	
	public func __hx_getField(field : String?, throwErrors : Bool, isCheck : Bool, handleProperties : Bool) ->  Any?
	
	public func __hx_getField_f(field : String?, throwErrors : Bool, handleProperties : Bool) ->  Double
	
	public func __hx_invokeField(field : String?, dynargs : haxe.root.Array) ->  Any?
	
	public func __hx_getFields(baseArr : haxe.root.Array<String??>) ->  Void
	
}


