// Generated by Haxe 3.3.0
package haxe.lang;

import haxe.root.*;

public class ParamEnum : haxe.lang.Enum
{
	public init(index : Int, params : haxe.root.Array) ->  Void
	{
		//line 101 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		super(index)
		//line 102 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		this!.params = params
	}
	
	
	public dynamic func params haxe.root.Array
	
	public override func getParams() ->  haxe.root.Array<Any?>
	{
		//line 107 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if ((this!.params == nil)) 
		{
			//line 107 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return haxe.root.Array<Any?>([])
		}
		else
		{
			//line 107 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return (haxe.ds._Vector.Vector_Impl_.toArray(this!.params)) as haxe.root.Array<Any?>
		}
		
	}
	
	
	public override func toString() ->  String?
	{
		//line 112 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if (((this!.params == nil) || ((this!.params) as haxe.root.Array!.length == 0))) 
		{
			//line 112 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return this!.getTag()
		}
		
		//line 113 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		var ret : haxe.root.StringBuf = haxe.root.StringBuf()
		//line 114 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		ret!.add(this!.getTag())
		//line 114 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		ret!.add("(")
		//line 115 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		var first : Bool = true
		//line 116 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		{
			//line 116 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			var _g : Int = 0
			//line 116 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			var _g1 : haxe.root.Array = this!.params
			//line 116 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			while ((_g < (_g1) as haxe.root.Array!.length))
			{
				//line 116 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				var p : Any? = ((_g1) as haxe.root.Array!.__get(_g)) as Any?
				//line 116 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				 ++ _g
				//line 118 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				if (first) 
				{
					//line 119 "/home/ron/haxe/std/swift/internal/HxObject.hx"
					first = false
				}
				else
				{
					//line 121 "/home/ron/haxe/std/swift/internal/HxObject.hx"
					ret!.add(",")
				}
				
				//line 122 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				ret!.add(p)
			}
			
		}
		
		//line 124 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		ret!.add(")")
		//line 125 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		return ret!.toString()
	}
	
	
	public func equals(obj : Any?) ->  Bool
	{
		//line 130 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if ((obj == this)) 
		{
			//line 131 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return true
		}
		
		//line 132 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		var obj1 : haxe.lang.ParamEnum = ( (haxe.root.Std.is(obj, haxe.lang.ParamEnum)) ? ((obj) as haxe.lang.ParamEnum) : (nil) )
		//line 134 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if ( ! (((((obj1 != nil) && haxe.root.Std.is(obj1, haxe.root.Type.getEnum((this) as Any?))) && (obj1!.index == this!.index)))) ) 
		{
			//line 135 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return false
		}
		
		//line 136 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if ((obj1!.params == this!.params)) 
		{
			//line 137 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return true
		}
		
		//line 138 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		var len : Int = 0
		//line 139 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		var tmp : Bool = false
		//line 139 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if ( ! ((((obj1!.params == nil) || (this!.params == nil)))) ) 
		{
			//line 139 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			len = (this!.params) as haxe.root.Array!.length
			//line 139 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			tmp = (len != (obj1!.params) as haxe.root.Array!.length)
		}
		else
		{
			//line 139 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			tmp = true
		}
		
		//line 139 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if (tmp) 
		{
			//line 140 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			return false
		}
		
		//line 141 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		{
			//line 141 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			var _g1 : Int = 0
			//line 141 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			var _g : Int = len
			//line 141 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			while ((_g1 < _g))
			{
				//line 141 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				var i : Int = _g1++
				//line 143 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				if ( ! (haxe.root.Type.enumEq(((obj1!.params) as haxe.root.Array!.__get(i)) as Any?, ((this!.params) as haxe.root.Array!.__get(i)) as Any?)) ) 
				{
					//line 144 "/home/ron/haxe/std/swift/internal/HxObject.hx"
					return false
				}
				
			}
			
		}
		
		//line 146 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		return true
	}
	
	
	public func hashCode() ->  Int
	{
		//line 151 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		var h : Int = 19
		//line 152 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		if ((this!.params != nil)) 
		{
			//line 152 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			var _g : Int = 0
			//line 152 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			var _g1 : haxe.root.Array = this!.params
			//line 152 "/home/ron/haxe/std/swift/internal/HxObject.hx"
			while ((_g < (_g1) as haxe.root.Array!.length))
			{
				//line 152 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				var p : Any? = ((_g1) as haxe.root.Array!.__get(_g)) as Any?
				//line 152 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				 ++ _g
				//line 154 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				h *= 31
				//line 155 "/home/ron/haxe/std/swift/internal/HxObject.hx"
				if ((p != nil)) 
				{
					//line 156 "/home/ron/haxe/std/swift/internal/HxObject.hx"
					h += (haxe.lang.Runtime.callField(p, "hashCode", nil)) as Any?
				}
				
			}
			
		}
		
		//line 158 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		h += this!.index
		//line 159 "/home/ron/haxe/std/swift/internal/HxObject.hx"
		return h
	}
	
	
}


