// Generated by Haxe 3.3.0
package haxe.lang;

import haxe.root.*;

public class Runtime
{
	public class dynamic func undefined Any? = (haxe.lang.DynamicObject([], [], [], [])) as Any?
	
	public class func closure(obj : Any?, field : String?) ->  Any?
	{
		
	
	}
	
	
	public class func eq(v1 : Any?, v2 : Any?) ->  Bool
	{
		
	
	}
	
	
	public class func refEq(v1 : Any?, v2 : Any?) ->  Bool
	{
		
	
	}
	
	
	public class func valEq(v1 : Any?, v2 : Any?) ->  Bool
	{
		
	
	}
	
	
	public class func toDouble(obj : Any?) ->  Double
	{
		
	
	}
	
	
	public class func toBool(obj : Any?) ->  Bool
	{
		
	
	}
	
	
	public class func toInt(obj : Any?) ->  Int
	{
		
	
	}
	
	
	public class func toLong(obj : Any?) ->  Int64
	{
		//line 86 "/home/ron/haxe/std/swift/internal/Runtime.hx"
		return swift._StdTypes.Int64_Impl_._new()
	}
	
	
	public class func isDouble(obj : Any?) ->  Bool
	{
		
	
	}
	
	
	public class func isInt(obj : Any?) ->  Bool
	{
		//line 98 "/home/ron/haxe/std/swift/internal/Runtime.hx"
		return false
	}
	
	
	public class func slowHasField(o : Any?, field : String?) ->  Bool
	{
		
	
	}
	
	
	public class func compare(v1 : Any?, v2 : Any?) ->  Int
	{
		
	}
	
	
	public class func plus(v1 : Any?, v2 : Any?) ->  Any?
	{
		
	
	}
	
	
	public class func slowGetField(obj : Any?, field : String?, throwErrors : Bool) ->  Any?
	{
		
	
	}
	
	
	public class func slowSetField(obj : Any?, field : String?, value : Any?) ->  Any?
	{
		
	
	}
	
	
	public class func slowCallField(obj : Any?, field : String?, args : haxe.root.Array) ->  Any?
	{
		
	
	}
	
	
	public class func callField(obj : Any?, field : String?, args : haxe.root.Array) ->  Any?
	{
		
	
	}
	
	
	public class func getField(obj : Any?, field : String?, throwErrors : Bool) ->  Any?
	{
		
	
	}
	
	
	public class func getField_f(obj : Any?, field : String?, throwErrors : Bool) ->  Double
	{
		
	
	}
	
	
	public class func setField(obj : Any?, field : String?, value : Any?) ->  Any?
	{
		
	
	}
	
	
	public class func setField_f(obj : Any?, field : String?, value : Double) ->  Double
	{
		
	
	}
	
	
	public class func toString(obj : Any?) ->  String?
	{
		//line 179 "/home/ron/haxe/std/swift/internal/Runtime.hx"
		return ""
	}
	
	
	public class func isFinite(v : Double) ->  Bool
	{
		//line 184 "/home/ron/haxe/std/swift/internal/Runtime.hx"
		return false
	}
	
	
}


