// Generated by Haxe 3.3.0
package haxe.lang;

import haxe.root.*;

public class VarArgsBase : haxe.lang.Function
{
	public override func __hx_invokeDynamic(dynArgs : haxe.root.Array) ->  Any?
	{
		//line 44 "/home/ron/haxe/std/swift/internal/Function.hx"
		throw "Abstract implementation"
	}
	
	
	public override func __hx_invoke6_o(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?, __fn_float3 : Double, __fn_dyn3 : Any?, __fn_float4 : Double, __fn_dyn4 : Any?, __fn_float5 : Double, __fn_dyn5 : Any?, __fn_float6 : Double, __fn_dyn6 : Any?) ->  Any?
	{
		//line 40 "/home/ron/haxe/std/swift/internal/Function.hx"
		return this!.__hx_invokeDynamic(haxe.root.Array<Any?>([]))
	}
	
	
	public override func __hx_invoke6_f(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?, __fn_float3 : Double, __fn_dyn3 : Any?, __fn_float4 : Double, __fn_dyn4 : Any?, __fn_float5 : Double, __fn_dyn5 : Any?, __fn_float6 : Double, __fn_dyn6 : Any?) ->  Double
	{
		//line 40 "/home/ron/haxe/std/swift/internal/Function.hx"
		return (this!.__hx_invokeDynamic(haxe.root.Array<Any?>([]))) as Double
	}
	
	
	public override func __hx_invoke5_o(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?, __fn_float3 : Double, __fn_dyn3 : Any?, __fn_float4 : Double, __fn_dyn4 : Any?, __fn_float5 : Double, __fn_dyn5 : Any?) ->  Any?
	{
		//line 40 "/home/ron/haxe/std/swift/internal/Function.hx"
		return this!.__hx_invokeDynamic(haxe.root.Array<Any?>([]))
	}
	
	
	public override func __hx_invoke5_f(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?, __fn_float3 : Double, __fn_dyn3 : Any?, __fn_float4 : Double, __fn_dyn4 : Any?, __fn_float5 : Double, __fn_dyn5 : Any?) ->  Double
	{
		//line 40 "/home/ron/haxe/std/swift/internal/Function.hx"
		return (this!.__hx_invokeDynamic(haxe.root.Array<Any?>([]))) as Double
	}
	
	
	public override func __hx_invoke4_o(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?, __fn_float3 : Double, __fn_dyn3 : Any?, __fn_float4 : Double, __fn_dyn4 : Any?) ->  Any?
	{
		//line 40 "/home/ron/haxe/std/swift/internal/Function.hx"
		return this!.__hx_invokeDynamic(haxe.root.Array<Any?>([]))
	}
	
	
	public override func __hx_invoke4_f(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?, __fn_float3 : Double, __fn_dyn3 : Any?, __fn_float4 : Double, __fn_dyn4 : Any?) ->  Double
	{
		//line 40 "/home/ron/haxe/std/swift/internal/Function.hx"
		return (this!.__hx_invokeDynamic(haxe.root.Array<Any?>([]))) as Double
	}
	
	
	public override func __hx_invoke3_o(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?, __fn_float3 : Double, __fn_dyn3 : Any?) ->  Any?
	{
		//line 40 "/home/ron/haxe/std/swift/internal/Function.hx"
		return this!.__hx_invokeDynamic(haxe.root.Array<Any?>([]))
	}
	
	
	public override func __hx_invoke3_f(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?, __fn_float3 : Double, __fn_dyn3 : Any?) ->  Double
	{
		//line 40 "/home/ron/haxe/std/swift/internal/Function.hx"
		return (this!.__hx_invokeDynamic(haxe.root.Array<Any?>([]))) as Double
	}
	
	
	public override func __hx_invoke2_o(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?) ->  Any?
	{
		//line 40 "/home/ron/haxe/std/swift/internal/Function.hx"
		return this!.__hx_invokeDynamic(haxe.root.Array<Any?>([]))
	}
	
	
	public override func __hx_invoke2_f(__fn_float1 : Double, __fn_dyn1 : Any?, __fn_float2 : Double, __fn_dyn2 : Any?) ->  Double
	{
		//line 40 "/home/ron/haxe/std/swift/internal/Function.hx"
		return (this!.__hx_invokeDynamic(haxe.root.Array<Any?>([]))) as Double
	}
	
	
	public override func __hx_invoke1_o(__fn_float1 : Double, __fn_dyn1 : Any?) ->  Any?
	{
		//line 40 "/home/ron/haxe/std/swift/internal/Function.hx"
		return this!.__hx_invokeDynamic(haxe.root.Array<Any?>([]))
	}
	
	
	public override func __hx_invoke1_f(__fn_float1 : Double, __fn_dyn1 : Any?) ->  Double
	{
		//line 40 "/home/ron/haxe/std/swift/internal/Function.hx"
		return (this!.__hx_invokeDynamic(haxe.root.Array<Any?>([]))) as Double
	}
	
	
	public override func __hx_invoke0_o() ->  Any?
	{
		//line 40 "/home/ron/haxe/std/swift/internal/Function.hx"
		return this!.__hx_invokeDynamic(nil)
	}
	
	
	public override func __hx_invoke0_f() ->  Double
	{
		//line 40 "/home/ron/haxe/std/swift/internal/Function.hx"
		return (this!.__hx_invokeDynamic(nil)) as Double
	}
	
	
}


