// Generated by Haxe 3.3.0
package haxe.lang;

import haxe.root.*;

public class VarArgsFunction : haxe.lang.VarArgsBase
{
	public init(fun : ( haxe.root.Array ) -> Any?) ->  Void
	{
		//line 54 "/home/ron/haxe/std/swift/internal/Function.hx"
		super(-1, -1)
		//line 55 "/home/ron/haxe/std/swift/internal/Function.hx"
		this!.fun = fun
	}
	
	
	public dynamic func fun ( haxe.root.Array ) -> Any?
	
	public override func __hx_invokeDynamic(dynArgs : haxe.root.Array) ->  Any?
	{
		//line 60 "/home/ron/haxe/std/swift/internal/Function.hx"
		return this!.fun(dynArgs)
	}
	
	
}


