// Generated by Haxe 3.3.0
package haxe.ds._Vector;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public final class Vector_Impl_
{
	
	
	public static <T> haxe.root.Array<T> toArray(T[] this1)
	{
		//line 190 "/home/ron/haxe/std/haxe/ds/Vector.hx"
		haxe.root.Array<T> a = new haxe.root.Array<T>();
		//line 191 "/home/ron/haxe/std/haxe/ds/Vector.hx"
		int len = ((T[]) (this1) ).length;
		//line 196 "/home/ron/haxe/std/haxe/ds/Vector.hx"
		{
			//line 196 "/home/ron/haxe/std/haxe/ds/Vector.hx"
			int _g1 = 0;
			//line 196 "/home/ron/haxe/std/haxe/ds/Vector.hx"
			while (( _g1 < len ))
			{
				//line 196 "/home/ron/haxe/std/haxe/ds/Vector.hx"
				int i = _g1++;
				//line 197 "/home/ron/haxe/std/haxe/ds/Vector.hx"
				a.__set(i, ((T) (((T[]) (this1) )[i]) ));
			}
			
		}
		
		//line 198 "/home/ron/haxe/std/haxe/ds/Vector.hx"
		return a;
	}
	
	
}


