// Generated by Haxe 3.3.0
package _Array;

import haxe.root.*;

@SuppressWarnings(value={})
public final class ArrayIterator<T>
{
	public ArrayIterator(haxe.root.Array<T?> a)
	{
		//line 399 "/home/ron/haxe/std/swift/_std/Array.hx"
		this.arr = a
		//line 400 "/home/ron/haxe/std/swift/_std/Array.hx"
		this.len = a.length
		//line 401 "/home/ron/haxe/std/swift/_std/Array.hx"
		this.i = 0
	}
	
	
	public haxe.root.Array<T?> arr
	
	public Int len
	
	public Int i
	
	public final Bool hasNext()
	{
		//line 404 "/home/ron/haxe/std/swift/_std/Array.hx"
		return ( this.i < this.len )
	}
	
	
	public final T next()
	{
		//line 405 "/home/ron/haxe/std/swift/_std/Array.hx"
		return this.arr[this.i++]
	}
	
	
}


