// Generated by Haxe 3.3.0
package haxe.ds._Vector;

import haxe.root.*;

@SuppressWarnings(value={})
public final class Vector_Impl_
{
	
	
	public static <T> haxe.root.Array<T?> toArray(haxe.root.Array<T?> this1)
	{
		//line 190 "/home/ron/haxe/std/haxe/ds/Vector.hx"
		haxe.root.Array<T?> a = new haxe.root.Array<T?>()
		//line 191 "/home/ron/haxe/std/haxe/ds/Vector.hx"
		Int len = ((haxe.root.Array<T?>) (this1) ).length
		//line 196 "/home/ron/haxe/std/haxe/ds/Vector.hx"
		{
			//line 196 "/home/ron/haxe/std/haxe/ds/Vector.hx"
			Int _g1 = 0
			//line 196 "/home/ron/haxe/std/haxe/ds/Vector.hx"
			while (( _g1 < len ))
			{
				//line 196 "/home/ron/haxe/std/haxe/ds/Vector.hx"
				Int i = _g1++
				//line 197 "/home/ron/haxe/std/haxe/ds/Vector.hx"
				a[i] = ((T) (((haxe.root.Array<T?>) (this1) )[i]) )
			}
			
		}
		
		//line 198 "/home/ron/haxe/std/haxe/ds/Vector.hx"
		return a
	}
	
	
}


