// Generated by Haxe 3.3.0
package haxe;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Log extends haxe.lang.HxObject
{
	static
	{
		//line 47 "/home/ron/haxe/std/haxe/Log.hx"
		haxe.Log.trace = ( (( haxe.Log_Anon_47__Fun.__hx_current != null )) ? (haxe.Log_Anon_47__Fun.__hx_current) : (haxe.Log_Anon_47__Fun.__hx_current = ((haxe.Log_Anon_47__Fun) (new haxe.Log_Anon_47__Fun()) )) );
	}
	
	public Log(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Log()
	{
		//line 28 "/home/ron/haxe/std/haxe/Log.hx"
		haxe.Log.__hx_ctor_haxe_Log(this);
	}
	
	
	public static void __hx_ctor_haxe_Log(haxe.Log __temp_me7)
	{
	}
	
	
	public static haxe.lang.Function trace;
	
}


