// Generated by Haxe 3.3.0
package haxe;

import haxe.root.*;

@SuppressWarnings(value={})
public class Log
{
	static
	{
		//line 47 "/home/ron/haxe/std/haxe/Log.hx"
		haxe.Log.trace = [ func decl not supported ]
	}
	
	public static [ !TypeError v : Dynamic -> ?infos : Null<haxe.PosInfos> -> Void ] trace
	
}


