// Generated by Haxe 3.3.0
#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"/home/ron/haxe/std/cpp/_std/Std.hx",
"/home/ron/haxe/std/haxe/Log.hx",
"?",
"Main.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"/home/ron/haxe/std/cpp/_std/Std.hx",
"/home/ron/haxe/std/haxe/Log.hx",
"?",
"/home/ron/haxesrc/Hello/Main.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"Main",
"Std",
"haxe.Log",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(hx::__hxcpp_all_classes, hx::__hxcpp_all_files_fullpath); }
