// Generated by Haxe 3.3.0
package haxe.root;

import haxe.root.*;

public class Hello : haxe.lang.HxObject
{
	public class dynamic func __rtti String? = "<class path=\"Hello\" params=\"\">\n\t<main public=\"1\" set=\"method\" line=\"4\" static=\"1\">\n\t\t<f a=\"\"><x path=\"Void\"/></f>\n\t\t<meta><m n=\":keep\"/></meta>\n\t</main>\n\t<meta><m n=\":rtti\"/></meta>\n</class>"
	
	public class func main() ->  Void
	{
		//line 6 "/home/ron/haxesrc/Hello/Hello.hx"
		haxe.Log.trace("Hello world", haxe.lang.DynamicObject([], [], [], []))
	}
	
	
}


