// Generated by Haxe 3.3.0
package haxe.root;

import haxe.root.*;

public class Reflect : haxe.lang.HxObject
{
	public class func hasField(o : Any?, field : String?) ->  Bool
	{
		//line 30 "/home/ron/haxe/std/swift/_std/Reflect.hx"
		return false
	}
	
	
	public class func field(o : Any?, field : String?) ->  Any?
	{
		//line 36 "/home/ron/haxe/std/swift/_std/Reflect.hx"
		return nil
	}
	
	
	public class func setField(o : Any?, field : String?, value : Any?) ->  Void
	{
	}
	
	
	public class func getProperty(o : Any?, field : String?) ->  Any?
	{
		//line 47 "/home/ron/haxe/std/swift/_std/Reflect.hx"
		return nil
	}
	
	
	public class func setProperty(o : Any?, field : String?, value : Any?) ->  Void
	{
	}
	
	
	public class func callMethod(o : Any?, func : Any?, args : haxe.root.Array) ->  Any?
	{
		//line 58 "/home/ron/haxe/std/swift/_std/Reflect.hx"
		return nil
	}
	
	
	public class func fields(o : Any?) ->  haxe.root.Array<String??>
	{
		//line 64 "/home/ron/haxe/std/swift/_std/Reflect.hx"
		return nil
	}
	
	
	public class func isFunction(f : Any?) ->  Bool
	{
		//line 70 "/home/ron/haxe/std/swift/_std/Reflect.hx"
		return false
	}
	
	
	public class func compare <T>(a : T, b : T) ->  Int
	{
		//line 76 "/home/ron/haxe/std/swift/_std/Reflect.hx"
		return 0
	}
	
	
	public class func compareMethods(f1 : Any?, f2 : Any?) ->  Bool
	{
		//line 82 "/home/ron/haxe/std/swift/_std/Reflect.hx"
		return false
	}
	
	
	public class func isObject(v : Any?) ->  Bool
	{
		//line 88 "/home/ron/haxe/std/swift/_std/Reflect.hx"
		return false
	}
	
	
	public class func isEnumValue(v : Any?) ->  Bool
	{
		//line 94 "/home/ron/haxe/std/swift/_std/Reflect.hx"
		return false
	}
	
	
	public class func deleteField(o : Any?, field : String?) ->  Bool
	{
		//line 100 "/home/ron/haxe/std/swift/_std/Reflect.hx"
		return false
	}
	
	
	public class func copy <T>(o : T) ->  T
	{
		//line 106 "/home/ron/haxe/std/swift/_std/Reflect.hx"
		return o
	}
	
	
	public class func makeVarArgs(f : ( haxe.root.Array ) -> Any?) ->  Any?
	{
		//line 113 "/home/ron/haxe/std/swift/_std/Reflect.hx"
		return nil
	}
	
	
}


